/**
 * Every text the app shows, in Catalan. Keep UI strings here instead of scattering them in components.
 */

const plural = (n: number, one: string, many: string) => (n === 1 ? one : many);

export const T = {
  appName: 'Finances',

  common: {
    save: 'Guardar',
    cancel: 'Cancel·lar',
    delete: 'Eliminar',
    edit: 'Editar',
    close: 'Tancar',
    back: 'Enrere',
    add: 'Afegir',
    continue: 'Continuar',
    today: 'Avui',
    yesterday: 'Ahir',
    optional: 'opcional',
    loading: 'Carregant…',
    income: 'Ingressos',
    expenses: 'Despeses',
    total: 'Total',
    remove: 'Treure',
    apply: 'Aplicar',
    yes: 'Sí',
    no: 'No',
    error: "S'ha produït un error. Torna-ho a provar.",
  },

  nav: {
    main: 'Navegació principal',
    dashboard: 'Resum',
    movements: 'Moviments',
    analysis: 'Anàlisi',
    wealth: 'Patrimoni',
    more: 'Més',
    addMovement: 'Afegir moviment',
  },

  types: {
    expense: 'Despesa',
    income: 'Ingrés',
    transfer: 'Transferència',
  },

  accountTypes: {
    corrent: 'Corrent',
    remunerat: 'Remunerat',
    efectiu: 'Efectiu',
    altre: 'Altre',
  },

  groups: {
    necessitats: 'Necessitats',
    oci: 'Oci i consum',
    altres: 'Altres',
  },

  source: {
    manual: 'Manual',
    recurring: 'Recurrent',
    interest: 'Interessos',
  },

  month: {
    previous: 'Mes anterior',
    next: 'Mes següent',
    pick: 'Tria el mes',
    current: 'Mes actual',
    previousYear: 'Any anterior',
    nextYear: 'Any següent',
  },

  onboarding: {
    welcomeTitle: 'Controla els teus diners',
    welcomeBody: 'Registra ingressos i despeses en segons, segueix els pressupostos i mira com evoluciona el teu patrimoni.',
    points: [
      'Quant ingresses i quant gastes cada mes, i en què.',
      "La teva taxa d'estalvi i si compleixes els pressupostos.",
      'El saldo de cada compte i el patrimoni total.',
    ],
    privacy: "Les dades es guarden només en aquest dispositiu: no hi ha comptes d'usuari ni núvol.",
    start: 'Començar',
    restore: 'Restaurar una còpia de seguretat',
    accountsTitle: 'Els teus comptes',
    accountsBody: 'Indica el saldo que té cada compte en una data. Ho pots canviar tot més endavant.',
    suggested: ['Compte corrent', 'Compte remunerat', 'Efectiu'],
    addAccount: 'Afegir un altre compte',
    addAccountHint: 'Si tens diners en diversos comptes (per exemple, dos de remunerats), afegeix-los tots.',
    addOfType: (type: string) => `Afegir un compte ${type.toLowerCase()}`,
    defaultNames: { corrent: 'Compte corrent', remunerat: 'Compte remunerat', efectiu: 'Efectiu', altre: 'Compte' },
    total: 'Patrimoni inicial',
    accountsCount: (n: number) => `${n} ${plural(n, 'compte', 'comptes')}`,
    removeAccount: 'Treure aquest compte',
    needOne: 'Cal com a mínim un compte per continuar.',
    finish: 'Continuar',
  },

  dashboard: {
    title: 'Resum',
    income: 'Ingressos',
    expenses: 'Despeses',
    balance: 'Balanç',
    wealth: 'Patrimoni líquid',
    surplus: 'Superàvit',
    deficit: 'Dèficit',
    savingsRate: (pct: string) => `Estalvi ${pct}`,
    wealthToday: 'avui',
    wealthAt: (date: string) => `a ${date}`,
    positiveMessage: 'Has generat superàvit aquest mes.',
    negativeMessage: 'Aquest mes has gastat més del que has ingressat.',
    emptyMonth: 'Encara no hi ha moviments aquest mes',
    emptyMonthHint: 'Toca el botó + per afegir el primer.',
    pace: 'Ritme de despesa',
    paceDays: (d: number, n: number) => `Dia ${d} de ${n}`,
    paceSpent: 'Despesa actual',
    paceBudget: 'Pressupost utilitzat',
    paceProjected: 'Despesa projectada',
    paceWarning: '⚠️ Estàs gastant més ràpid del previst.',
    paceText: (amount: string) => `Al ritme actual acabaràs gastant aproximadament ${amount} aquest mes.`,
    byCategory: 'Despeses per categoria',
    noExpenses: 'Encara no hi ha despeses aquest mes',
    restSlice: 'Resta de categories',
    seeMovements: (name: string) => `Veure els moviments de ${name}`,
  },

  movements: {
    title: 'Moviments',
    search: 'Cerca per descripció o notes',
    searchPlaceholder: 'Cerca',
    clearSearch: 'Esborrar la cerca',
    filters: 'Filtres',
    type: 'Tipus',
    category: 'Categoria',
    account: 'Compte',
    dateRange: 'Rang de dates',
    pickDate: 'Tria una data',
    from: 'Des de',
    to: 'Fins a',
    allTypes: 'Tots',
    allCategories: 'Totes',
    allAccounts: 'Tots',
    clearFilters: 'Treure els filtres',
    showResults: 'Veure els resultats',
    removeFilter: (label: string) => `Treure el filtre ${label}`,
    rangeChip: (from: string, to: string) => `${from} – ${to}`,
    rangeFromChip: (from: string) => `Des de ${from}`,
    rangeToChip: (to: string) => `Fins a ${to}`,
    rangeActive: 'El rang de dates substitueix el mes seleccionat.',
    empty: 'Encara no hi ha moviments aquest mes',
    emptyHint: 'Toca el botó + per afegir-ne un.',
    noMatches: 'Cap moviment coincideix amb la cerca o els filtres',
    recurringMark: 'Recurrent',
    interestMark: 'Interessos',
    count: (n: number) => `${n} ${plural(n, 'moviment', 'moviments')}`,
  },

  detail: {
    title: 'Detall del moviment',
    type: 'Tipus',
    category: 'Categoria',
    account: 'Compte',
    fromAccount: "Compte d'origen",
    toAccount: 'Compte de destinació',
    date: 'Data',
    description: 'Descripció',
    notes: 'Notes',
    source: 'Origen',
    deleteTitle: 'Eliminar aquest moviment?',
    deleteBody: 'Aquesta acció no es pot desfer.',
    recurringNote: "Es va crear a partir d'una regla recurrent. Editar-lo o eliminar-lo no afecta la regla.",
    interestNote: "Interessos calculats automàticament. Si l'edites o l'elimines, no es tornarà a generar.",
    deleted: 'Moviment eliminat',
  },

  form: {
    newTitle: 'Nou moviment',
    editTitle: 'Editar moviment',
    editRuleTitle: 'Editar moviment recurrent',
    amount: 'Import',
    category: 'Categoria',
    account: 'Compte',
    fromAccount: "Compte d'origen",
    toAccount: 'Compte de destinació',
    date: 'Data',
    description: 'Descripció',
    descriptionPlaceholder: 'Opcional',
    addNote: 'Afegir nota',
    notes: 'Notes',
    once: 'Pagament únic',
    recurring: 'Moviment recurrent',
    repeatEvery: 'Repeteix cada',
    frequency: { weekly: 'setmana', monthly: 'mes', yearly: 'any' },
    day: 'Dia',
    weekday: 'Dia de la setmana',
    startDate: "Data d'inici",
    endDate: 'Data de fi',
    noEndDate: 'Sense data de fi',
    lastDayHint: "Si el mes no té aquest dia, es farà servir l'últim dia del mes.",
    yearlyHint: (date: string) => `Es repetirà cada any el ${date}.`,
    backfillHint: "Es crearan ara els moviments des de la data d'inici fins avui.",
    saved: 'Moviment guardat',
    ruleSaved: 'Moviment recurrent guardat',
    ruleCreated: (n: number) =>
      n === 0 ? 'Moviment recurrent creat' : `Moviment recurrent creat · ${n} ${plural(n, 'moviment generat', 'moviments generats')}`,
    noAccounts: 'Primer crea un compte a Més → Comptes.',
  },

  validation: {
    amountRequired: 'Introdueix un import més gran que 0.',
    amountTooLarge: 'Aquest import és massa gran.',
    categoryRequired: 'Tria una categoria.',
    accountRequired: 'Tria un compte.',
    fromAccountRequired: "Tria el compte d'origen.",
    toAccountRequired: 'Tria el compte de destinació.',
    sameAccount: "El compte de destinació ha de ser diferent del d'origen.",
    dateRequired: 'Tria una data vàlida.',
    dateBeforeInitial: (account: string, date: string) => `La data no pot ser anterior al saldo inicial de «${account}» (${date}).`,
    endBeforeStart: "La data de fi no pot ser anterior a la d'inici.",
    nameRequired: 'Escriu un nom.',
    initialBalanceRequired: 'Introdueix el saldo inicial (pot ser 0).',
    initialAfterMovements: (date: string) => `Aquest compte té moviments des del ${date}: la data del saldo inicial no pot ser posterior.`,
    taeRange: 'Introdueix una TAE entre 0 i 50.',
    withholdingRange: 'Introdueix un percentatge entre 0 i 100.',
    emojiRequired: 'Tria un emoji.',
    amountInvalid: 'Introdueix un import vàlid.',
  },

  wealth: {
    title: 'Patrimoni',
    total: 'Patrimoni líquid total',
    distribution: 'Distribució',
    evolution: 'Evolució',
    ranges: { '30d': '30 dies', '3m': '3 mesos', '6m': '6 mesos', '12m': '12 mesos', all: "Tot l'historial" },
    rangesShort: { '30d': '30 d', '3m': '3 m', '6m': '6 m', '12m': '12 m', all: 'Tot' },
    vsPreviousMonth: 'Vs. mes anterior',
    vsPreviousMonthHint: (date: string) => `des del ${date}`,
    max: 'Màxim',
    min: 'Mínim',
    current: 'Saldo actual',
    noAccounts: 'Afegeix un compte per veure el teu patrimoni.',
    notStarted: 'Encara no hi ha dades: els saldos inicials comencen més endavant.',
  },

  budget: {
    title: 'Pressupost',
    defaultBadge: 'Per defecte',
    customBadge: 'Només aquest mes',
    defaultInfo: 'Estàs veient el pressupost per defecte, que s’aplica a tots els mesos sense pressupost propi.',
    customInfo: (month: string) => `Estàs veient un pressupost personalitzat només per a ${month}.`,
    customize: 'Personalitzar només aquest mes',
    resetToDefault: 'Tornar al per defecte',
    resetConfirmTitle: 'Tornar al pressupost per defecte?',
    resetConfirmBody: (month: string) => `S'eliminarà el pressupost personalitzat de ${month}.`,
    total: 'Pressupost total mensual',
    totalShort: 'Total mensual',
    perCategory: 'Per categoria',
    editHint: 'Deixa un camp buit si no hi vols pressupost.',
    near: 'A prop del límit',
    over: '⚠️ Pressupost superat',
    remaining: (amount: string) => `Queden ${amount}`,
    exceededBy: (amount: string) => `Superat en ${amount}`,
    none: 'Encara no hi ha cap pressupost',
    noneHint: "Defineix un pressupost total o per categories. És només informatiu: mai bloqueja cap despesa.",
    define: 'Definir el pressupost',
    noCategoryBudgets: 'Cap categoria té pressupost.',
    editingDefault: 'Editant el pressupost per defecte',
    editingCustom: (month: string) => `Editant el pressupost de ${month}`,
    saved: 'Pressupost guardat',
    informative: 'El pressupost és només informatiu: no bloqueja cap despesa.',
    spentOf: (spent: string, budget: string) => `${spent} / ${budget}`,
    noBudget: 'Sense pressupost',
    totalLine: 'Total del mes',
  },

  analysis: {
    title: 'Anàlisi',
    topCategory: 'Categoria amb més despesa',
    ofMonthTotal: (pct: string) => `${pct} del total del mes`,
    byCategory: 'Despeses per categoria',
    comparison: 'Comparació mensual',
    comparisonSubtitle: (current: string, previous: string) => `${current} vs. ${previous}`,
    perCategoryComparison: 'Per categoria',
    incomeVsExpenses: 'Ingressos vs despeses',
    expenseTrend: 'Evolució de despeses',
    monthlyBalance: 'Balanç mensual',
    savingsRate: "Taxa d'estalvi",
    lastSixMonths: 'Últims 6 mesos',
    noExpenses: 'Encara no hi ha despeses aquest mes',
    noData: 'Encara no hi ha dades',
    noChange: 'Sense canvis',
  },

  more: {
    title: 'Més',
    budget: 'Pressupost',
    budgetHint: 'Límits mensuals total i per categoria',
    accounts: 'Comptes',
    accountsHint: 'Saldos, tipus i interessos',
    categories: 'Categories',
    categoriesHint: 'Nom, emoji i color',
    recurring: 'Recurrents',
    recurringHint: 'Moviments que es repeteixen',
    data: 'Dades',
    dataHint: 'Exportar i còpies de seguretat',
    backupNever: 'Encara no has fet cap còpia de seguretat.',
    backupOld: (days: number) => `Fa ${days} dies que no fas cap còpia de seguretat.`,
    backupAction: 'Fer-ne una',
    version: (v: string) => `Versió ${v}`,
  },

  accounts: {
    title: 'Comptes',
    add: 'Nou compte',
    editTitle: 'Editar compte',
    newTitle: 'Nou compte',
    name: 'Nom',
    type: 'Tipus',
    color: 'Color',
    initialBalance: 'Saldo inicial',
    initialBalanceDate: 'Data del saldo inicial',
    tae: 'TAE (%)',
    withholding: 'Retenció (%)',
    taeHint: "Els interessos es calculen cada mes amb el saldo diari i s'afegeixen com a ingrés l'últim dia del mes.",
    taeLabel: (tae: string) => `TAE ${tae}`,
    movements: (n: number) => `${n} ${plural(n, 'moviment', 'moviments')}`,
    balance: 'Saldo actual',
    saved: 'Compte guardat',
    deleted: 'Compte eliminat',
    deleteTitle: (name: string) => `Eliminar «${name}»?`,
    deleteEmpty: 'Aquest compte no té moviments.',
    deleteWithMovements: (n: number) =>
      `Aquest compte té ${n} ${plural(n, 'moviment', 'moviments')}. Si l'elimines, també s'eliminaran, incloses les transferències amb altres comptes, i el patrimoni canviarà.`,
    deleteAcknowledge: (n: number) => `Entenc que s'eliminaran ${n} ${plural(n, 'moviment', 'moviments')}`,
    lastAccount: 'Ha de quedar com a mínim un compte.',
    empty: 'Encara no hi ha comptes',
    namePlaceholder: 'Ex.: Compte corrent',
  },

  categories: {
    title: 'Categories',
    expenses: 'Despeses',
    income: 'Ingressos',
    add: 'Nova categoria',
    newTitle: 'Nova categoria',
    editTitle: 'Editar categoria',
    name: 'Nom',
    emoji: 'Emoji',
    emojiHint: 'Escriu o enganxa un emoji.',
    color: 'Color',
    group: 'Grup',
    kind: 'Tipus',
    saved: 'Categoria guardada',
    deleted: 'Categoria eliminada',
    deleteTitle: (name: string) => `Eliminar «${name}»?`,
    deleteEmpty: 'Aquesta categoria no té moviments.',
    deleteUsage: (n: number, rules: number) => {
      const parts = [];
      if (n > 0) parts.push(`${n} ${plural(n, 'moviment', 'moviments')}`);
      if (rules > 0) parts.push(`${rules} ${plural(rules, 'regla recurrent', 'regles recurrents')}`);
      return `Té ${parts.join(' i ')}. Tria a quina categoria es mouen:`;
    },
    reassignTo: 'Moure a',
    lastOfKind: 'Ha de quedar com a mínim una categoria d’aquest tipus.',
    usage: (n: number) => `${n} ${plural(n, 'moviment', 'moviments')}`,
  },

  recurring: {
    title: 'Recurrents',
    empty: 'Encara no hi ha moviments recurrents',
    emptyHint: 'Crea’n un amb el botó + i l’opció «Moviment recurrent».',
    weekly: (weekday: string) => `Cada setmana · ${weekday}`,
    monthly: (day: number) => `Cada mes · dia ${day}`,
    yearly: (date: string) => `Cada any · ${date}`,
    next: (date: string) => `Propera: ${date}`,
    paused: 'Pausada',
    ended: 'Finalitzada',
    pause: 'Pausar',
    resume: 'Reprendre',
    paused_toast: 'Regla pausada',
    resumed_toast: 'Regla represa',
    deleteTitle: 'Eliminar aquesta regla?',
    deleteBody: 'Els moviments que ja s’han generat es mantindran.',
    deleted: 'Regla eliminada',
    until: (date: string) => `fins al ${date}`,
  },

  data: {
    title: 'Dades',
    localInfo:
      "Les dades només es guarden en aquest dispositiu. Si esborres l'app de la pantalla d'inici o les dades del navegador, es perden. Fes còpies de seguretat sovint i guarda-les en un lloc segur (per exemple, a iCloud Drive).",
    csvTitle: 'Exportar moviments a CSV',
    csvBody: 'Per obrir-los amb Excel o Numbers.',
    csvRange: 'Rang',
    csvAll: 'Tot',
    csvYear: 'Un any',
    csvMonth: 'Un mes',
    csvExport: 'Exportar CSV',
    csvEmpty: 'No hi ha moviments en aquest rang.',
    csvDone: (n: number) => `${n} ${plural(n, 'moviment exportat', 'moviments exportats')}`,
    backupTitle: 'Còpia de seguretat',
    backupBody: 'Un fitxer amb totes les dades: comptes, categories, moviments, regles, pressupostos i configuració.',
    backupExport: 'Fer còpia de seguretat',
    backupImport: 'Restaurar una còpia',
    backupDone: 'Còpia de seguretat creada',
    lastBackup: (when: string) => `Última còpia: ${when}`,
    never: 'mai',
    ago: (days: number) => (days === 0 ? 'avui' : days === 1 ? 'ahir' : `fa ${days} dies`),
    invalidBackup: 'El fitxer no és una còpia de seguretat vàlida.',
    restoreTitle: 'Restaurar aquesta còpia?',
    restoreBody: (date: string, current: number, incoming: number) =>
      `Còpia del ${date}. Substituirà totes les dades actuals (${current} ${plural(current, 'moviment', 'moviments')}) per les de la còpia (${incoming} ${plural(incoming, 'moviment', 'moviments')}).`,
    restoreConfirm: 'Substituir les dades',
    restored: 'Còpia restaurada',
    wipeTitle: 'Esborrar totes les dades',
    wipeBody: 'Elimina tots els comptes, moviments, regles i pressupostos d’aquest dispositiu.',
    wipeConfirm1Title: 'Esborrar totes les dades?',
    wipeConfirm1Body: 'Es perdran tots els comptes, moviments, regles i pressupostos. Si no tens una còpia de seguretat, no es podran recuperar.',
    wipeConfirm2Title: 'N’estàs segur?',
    wipeConfirm2Body: 'Aquesta és l’última confirmació. Aquesta acció no es pot desfer.',
    wipeConfirm2Action: 'Sí, esborrar-ho tot',
    persistent: 'Emmagatzematge persistent activat',
    notPersistent: 'El navegador no garanteix que conservi les dades: fes còpies de seguretat.',
  },

  csv: {
    header: ['Data', 'Tipus', 'Import', 'Categoria', 'Compte', 'Compte destinació', 'Descripció', 'Notes'],
    fileName: (suffix: string) => `moviments-${suffix}.csv`,
    shareTitle: 'Moviments',
  },

  backup: {
    fileName: (date: string) => `finances-copia-${date}.json`,
  },

  interest: {
    description: (monthYear: string) => `Interessos ${monthYear}`,
  },

  update: {
    offlineReady: "L'app ja funciona sense connexió",
  },
} as const;
